/* Copyright 2009 The Stajistics Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.stajistics.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import org.stajistics.Stats;
import org.stajistics.StatsKey;
import org.stajistics.jdbc.decorator.AbstractPreparedStatementDecorator;
import org.stajistics.tracker.StatsTracker;

/**
 * 
 * 
 * 
 * @author The Stajistics Project
 */
public class StatsPreparedStatementWrapper extends AbstractPreparedStatementDecorator {

    private final Connection connection;
    private final String sql;
    private final StatsJDBCConfig config;

    private final StatsTracker openClosedTracker;

    public StatsPreparedStatementWrapper(final PreparedStatement delegate,
                                         final Connection connection,
                                         final String sql,
                                         final StatsJDBCConfig config) {
        super(delegate);

        if (connection == null) {
            throw new NullPointerException("connection");
        }
        if (sql == null) {
            throw new NullPointerException("sql");
        }
        if (config == null) {
            throw new NullPointerException("config");
        }

        this.connection = connection;
        this.sql = sql;
        this.config = config;

        StatsKey openClosedKey = JDBCStatsKeyConstants.PREPARED_STATEMENT
                                                      .buildCopy()
                                                      .withNameSuffix("open")
                                                      .newKey();

        openClosedTracker = Stats.track(openClosedKey);        
    }

    @Override
    public Connection getConnection() throws SQLException {
        return connection;
    }

    private void handleSQL(final String sql) {
        config.getSQLAnalyzer()
              .analyzeSQL(sql);
    }

    @Override
    public void close() throws SQLException {
        try {
            super.close();
        } finally {
            openClosedTracker.commit();
        }
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        handleSQL(sql);
        return delegate().execute(sql);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys)
            throws SQLException {
        handleSQL(sql);
        return delegate().execute(sql, autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        handleSQL(sql);
        return delegate().execute(sql, columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames)
            throws SQLException {
        handleSQL(sql);
        return delegate().execute(sql, columnNames);
    }    private volatile boolean initialized = false;

    @Override
    public ResultSet executeQuery() throws SQLException {
        return new StatsResultSetWrapper(delegate().executeQuery(), config);
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        handleSQL(sql);
        return new StatsResultSetWrapper(delegate().executeQuery(sql), config);
    }

    public String getSQL() {
        return sql;
    }
}