/* Copyright 2009 The Stajistics Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.stajistics.jdbc;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import org.stajistics.Stats;
import org.stajistics.StatsKey;
import org.stajistics.aop.ProxyFactory;
import org.stajistics.jdbc.decorator.AbstractConnectionDecorator;
import org.stajistics.tracker.StatsTracker;

/**
 * 
 * 
 *
 * @author The Stajistics Project
 */
public class StatsConnectionWrapper extends AbstractConnectionDecorator {

    private final StatsTracker openClosedTracker;

    private ProxyFactory<Statement> statementProxyFactory = ProxyFactory.NO_OP;
    private ProxyFactory<CallableStatement> callableStatementProxyFactory = ProxyFactory.NO_OP;
    private ProxyFactory<PreparedStatement> preparedStatementProxyFactory = ProxyFactory.NO_OP;

    public StatsConnectionWrapper(final Connection delegate) {
        this(delegate, 
             JDBCStatsKeyConstants.CONNECTION
                                  .buildCopy()
                                  .withNameSuffix("open")
                                  .newKey());
    }

    public StatsConnectionWrapper(final Connection delegate,
                                  final StatsKey openClosedKey) {
        super(delegate);

        if (openClosedKey == null) {
            throw new NullPointerException("openClosedKey");
        }

        openClosedTracker = Stats.track(openClosedKey);
    }

    @Override
    public void close() throws SQLException {
        try {
            delegate().close();
        } finally {
            openClosedTracker.commit();
        }
    }

    @Override
    public Statement createStatement() throws SQLException {
        Statement s = new StatsStatementWrapper(delegate().createStatement(), this);

        s = statementProxyFactory.createProxy(s);

        return s;
    }

    @Override
    public Statement createStatement(final int resultSetType, final int resultSetConcurrency) 
            throws SQLException {
        Statement s = new StatsStatementWrapper(delegate().createStatement(resultSetType, resultSetConcurrency), this);

        s = statementProxyFactory.createProxy(s);

        return s;
    }

    @Override
    public Statement createStatement(final int resultSetType, 
                                     final int resultSetConcurrency, 
                                     final int resultSetHoldability) 
            throws SQLException {
        Statement s = new StatsStatementWrapper(delegate().createStatement(resultSetType, resultSetConcurrency, resultSetHoldability), this);

        s = statementProxyFactory.createProxy(s);

        return s;
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        CallableStatement cs = new StatsCallableStatementWrapper(delegate().prepareCall(sql), this, sql);

        cs = callableStatementProxyFactory.createProxy(cs);

        return cs;
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) 
            throws SQLException {
        CallableStatement cs = new StatsCallableStatementWrapper(delegate().prepareCall(sql, resultSetType, resultSetConcurrency), this, sql);

        cs = callableStatementProxyFactory.createProxy(cs);

        return cs;
    }

    @Override
    public CallableStatement prepareCall(String sql,
                                         int resultSetType,
                                         int resultSetConcurrency,
                                         int resultSetHoldability) throws SQLException {
        CallableStatement cs = new StatsCallableStatementWrapper(delegate().prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability), this, sql);

        cs = callableStatementProxyFactory.createProxy(cs);

        return cs;
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        PreparedStatement ps = new StatsPreparedStatementWrapper(delegate().prepareStatement(sql), this, sql);

        ps = preparedStatementProxyFactory.createProxy(ps);

        return ps;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        PreparedStatement ps = new StatsPreparedStatementWrapper(delegate().prepareStatement(sql, autoGeneratedKeys), this, sql);

        ps = preparedStatementProxyFactory.createProxy(ps);

        return ps;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        PreparedStatement ps = new StatsPreparedStatementWrapper(delegate().prepareStatement(sql, columnIndexes), this, sql);

        ps = preparedStatementProxyFactory.createProxy(ps);

        return ps;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        PreparedStatement ps = new StatsPreparedStatementWrapper(delegate().prepareStatement(sql, columnNames), this, sql);

        ps = preparedStatementProxyFactory.createProxy(ps);

        return ps;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) 
            throws SQLException {
        PreparedStatement ps = new StatsPreparedStatementWrapper(delegate().prepareStatement(sql, resultSetType, resultSetConcurrency), this, sql);

        ps = preparedStatementProxyFactory.createProxy(ps);

        return ps;
    }

    @Override
    public PreparedStatement prepareStatement(String sql,
                                              int resultSetType,
                                              int resultSetConcurrency,
                                              int resultSetHoldability) throws SQLException {
        PreparedStatement ps = new StatsPreparedStatementWrapper(delegate().prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), this, sql);

        ps = preparedStatementProxyFactory.createProxy(ps);

        return ps;
    }
}
