/* Copyright 2009 The Stajistics Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.stajistics.jdbc.decorator;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Map;

/**
 * 
 * @author The Stajistics Project
 *
 */
public class AbstractCallableStatementDecorator extends AbstractWrapper implements CallableStatement {

    private final CallableStatement delegate;

    public AbstractCallableStatementDecorator(final CallableStatement delegate) {
        if (delegate == null) {
            throw new NullPointerException("delegate");
        }

        this.delegate = delegate;
    }

    @Override
    protected final CallableStatement delegate() {
        return delegate;
    }

    /**
     * @throws SQLException
     * @see java.sql.PreparedStatement#addBatch()
     */
    public void addBatch() throws SQLException {
        delegate().addBatch();
    }

    /**
     * @param sql
     * @throws SQLException
     * @see java.sql.Statement#addBatch(java.lang.String)
     */
    public void addBatch(String sql) throws SQLException {
        delegate().addBatch(sql);
    }

    /**
     * @throws SQLException
     * @see java.sql.Statement#cancel()
     */
    public void cancel() throws SQLException {
        delegate().cancel();
    }

    /**
     * @throws SQLException
     * @see java.sql.Statement#clearBatch()
     */
    public void clearBatch() throws SQLException {
        delegate().clearBatch();
    }

    /**
     * @throws SQLException
     * @see java.sql.PreparedStatement#clearParameters()
     */
    public void clearParameters() throws SQLException {
        delegate().clearParameters();
    }

    /**
     * @throws SQLException
     * @see java.sql.Statement#clearWarnings()
     */
    public void clearWarnings() throws SQLException {
        delegate().clearWarnings();
    }

    /**
     * @throws SQLException
     * @see java.sql.Statement#close()
     */
    public void close() throws SQLException {
        delegate().close();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.PreparedStatement#execute()
     */
    public boolean execute() throws SQLException {
        return delegate().execute();
    }

    /**
     * @param sql
     * @param autoGeneratedKeys
     * @return
     * @throws SQLException
     * @see java.sql.Statement#execute(java.lang.String, int)
     */
    public boolean execute(String sql, int autoGeneratedKeys)
            throws SQLException {
        return delegate().execute(sql, autoGeneratedKeys);
    }

    /**
     * @param sql
     * @param columnIndexes
     * @return
     * @throws SQLException
     * @see java.sql.Statement#execute(java.lang.String, int[])
     */
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return delegate().execute(sql, columnIndexes);
    }

    /**
     * @param sql
     * @param columnNames
     * @return
     * @throws SQLException
     * @see java.sql.Statement#execute(java.lang.String, java.lang.String[])
     */
    public boolean execute(String sql, String[] columnNames)
            throws SQLException {
        return delegate().execute(sql, columnNames);
    }

    /**
     * @param sql
     * @return
     * @throws SQLException
     * @see java.sql.Statement#execute(java.lang.String)
     */
    public boolean execute(String sql) throws SQLException {
        return delegate().execute(sql);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#executeBatch()
     */
    public int[] executeBatch() throws SQLException {
        return delegate().executeBatch();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.PreparedStatement#executeQuery()
     */
    public ResultSet executeQuery() throws SQLException {
        return delegate().executeQuery();
    }

    /**
     * @param sql
     * @return
     * @throws SQLException
     * @see java.sql.Statement#executeQuery(java.lang.String)
     */
    public ResultSet executeQuery(String sql) throws SQLException {
        return delegate().executeQuery(sql);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.PreparedStatement#executeUpdate()
     */
    public int executeUpdate() throws SQLException {
        return delegate().executeUpdate();
    }

    /**
     * @param sql
     * @param autoGeneratedKeys
     * @return
     * @throws SQLException
     * @see java.sql.Statement#executeUpdate(java.lang.String, int)
     */
    public int executeUpdate(String sql, int autoGeneratedKeys)
            throws SQLException {
        return delegate().executeUpdate(sql, autoGeneratedKeys);
    }

    /**
     * @param sql
     * @param columnIndexes
     * @return
     * @throws SQLException
     * @see java.sql.Statement#executeUpdate(java.lang.String, int[])
     */
    public int executeUpdate(String sql, int[] columnIndexes)
            throws SQLException {
        return delegate().executeUpdate(sql, columnIndexes);
    }

    /**
     * @param sql
     * @param columnNames
     * @return
     * @throws SQLException
     * @see java.sql.Statement#executeUpdate(java.lang.String, java.lang.String[])
     */
    public int executeUpdate(String sql, String[] columnNames)
            throws SQLException {
        return delegate().executeUpdate(sql, columnNames);
    }

    /**
     * @param sql
     * @return
     * @throws SQLException
     * @see java.sql.Statement#executeUpdate(java.lang.String)
     */
    public int executeUpdate(String sql) throws SQLException {
        return delegate().executeUpdate(sql);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getArray(int)
     */
    public Array getArray(int parameterIndex) throws SQLException {
        return delegate().getArray(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getArray(java.lang.String)
     */
    public Array getArray(String parameterName) throws SQLException {
        return delegate().getArray(parameterName);
    }

    /**
     * @param parameterIndex
     * @param scale
     * @return
     * @throws SQLException
     * @deprecated
     * @see java.sql.CallableStatement#getBigDecimal(int, int)
     */
    public BigDecimal getBigDecimal(int parameterIndex, int scale)
            throws SQLException {
        return delegate().getBigDecimal(parameterIndex, scale);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getBigDecimal(int)
     */
    public BigDecimal getBigDecimal(int parameterIndex) throws SQLException {
        return delegate().getBigDecimal(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getBigDecimal(java.lang.String)
     */
    public BigDecimal getBigDecimal(String parameterName) throws SQLException {
        return delegate().getBigDecimal(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getBlob(int)
     */
    public Blob getBlob(int parameterIndex) throws SQLException {
        return delegate().getBlob(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getBlob(java.lang.String)
     */
    public Blob getBlob(String parameterName) throws SQLException {
        return delegate().getBlob(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getBoolean(int)
     */
    public boolean getBoolean(int parameterIndex) throws SQLException {
        return delegate().getBoolean(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getBoolean(java.lang.String)
     */
    public boolean getBoolean(String parameterName) throws SQLException {
        return delegate().getBoolean(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getByte(int)
     */
    public byte getByte(int parameterIndex) throws SQLException {
        return delegate().getByte(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getByte(java.lang.String)
     */
    public byte getByte(String parameterName) throws SQLException {
        return delegate().getByte(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getBytes(int)
     */
    public byte[] getBytes(int parameterIndex) throws SQLException {
        return delegate().getBytes(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getBytes(java.lang.String)
     */
    public byte[] getBytes(String parameterName) throws SQLException {
        return delegate().getBytes(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getCharacterStream(int)
     */
    public Reader getCharacterStream(int parameterIndex) throws SQLException {
        return delegate().getCharacterStream(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getCharacterStream(java.lang.String)
     */
    public Reader getCharacterStream(String parameterName) throws SQLException {
        return delegate().getCharacterStream(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getClob(int)
     */
    public Clob getClob(int parameterIndex) throws SQLException {
        return delegate().getClob(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getClob(java.lang.String)
     */
    public Clob getClob(String parameterName) throws SQLException {
        return delegate().getClob(parameterName);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getConnection()
     */
    public Connection getConnection() throws SQLException {
        return delegate().getConnection();
    }

    /**
     * @param parameterIndex
     * @param cal
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getDate(int, java.util.Calendar)
     */
    public Date getDate(int parameterIndex, Calendar cal) throws SQLException {
        return delegate().getDate(parameterIndex, cal);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getDate(int)
     */
    public Date getDate(int parameterIndex) throws SQLException {
        return delegate().getDate(parameterIndex);
    }

    /**
     * @param parameterName
     * @param cal
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getDate(java.lang.String, java.util.Calendar)
     */
    public Date getDate(String parameterName, Calendar cal) throws SQLException {
        return delegate().getDate(parameterName, cal);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getDate(java.lang.String)
     */
    public Date getDate(String parameterName) throws SQLException {
        return delegate().getDate(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getDouble(int)
     */
    public double getDouble(int parameterIndex) throws SQLException {
        return delegate().getDouble(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getDouble(java.lang.String)
     */
    public double getDouble(String parameterName) throws SQLException {
        return delegate().getDouble(parameterName);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getFetchDirection()
     */
    public int getFetchDirection() throws SQLException {
        return delegate().getFetchDirection();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getFetchSize()
     */
    public int getFetchSize() throws SQLException {
        return delegate().getFetchSize();
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getFloat(int)
     */
    public float getFloat(int parameterIndex) throws SQLException {
        return delegate().getFloat(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getFloat(java.lang.String)
     */
    public float getFloat(String parameterName) throws SQLException {
        return delegate().getFloat(parameterName);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getGeneratedKeys()
     */
    public ResultSet getGeneratedKeys() throws SQLException {
        return delegate().getGeneratedKeys();
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getInt(int)
     */
    public int getInt(int parameterIndex) throws SQLException {
        return delegate().getInt(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getInt(java.lang.String)
     */
    public int getInt(String parameterName) throws SQLException {
        return delegate().getInt(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getLong(int)
     */
    public long getLong(int parameterIndex) throws SQLException {
        return delegate().getLong(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getLong(java.lang.String)
     */
    public long getLong(String parameterName) throws SQLException {
        return delegate().getLong(parameterName);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getMaxFieldSize()
     */
    public int getMaxFieldSize() throws SQLException {
        return delegate().getMaxFieldSize();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getMaxRows()
     */
    public int getMaxRows() throws SQLException {
        return delegate().getMaxRows();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.PreparedStatement#getMetaData()
     */
    public ResultSetMetaData getMetaData() throws SQLException {
        return delegate().getMetaData();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getMoreResults()
     */
    public boolean getMoreResults() throws SQLException {
        return delegate().getMoreResults();
    }

    /**
     * @param current
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getMoreResults(int)
     */
    public boolean getMoreResults(int current) throws SQLException {
        return delegate().getMoreResults(current);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getNCharacterStream(int)
     */
    public Reader getNCharacterStream(int parameterIndex) throws SQLException {
        return delegate().getNCharacterStream(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getNCharacterStream(java.lang.String)
     */
    public Reader getNCharacterStream(String parameterName) throws SQLException {
        return delegate().getNCharacterStream(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getNClob(int)
     */
    public NClob getNClob(int parameterIndex) throws SQLException {
        return delegate().getNClob(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getNClob(java.lang.String)
     */
    public NClob getNClob(String parameterName) throws SQLException {
        return delegate().getNClob(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getNString(int)
     */
    public String getNString(int parameterIndex) throws SQLException {
        return delegate().getNString(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getNString(java.lang.String)
     */
    public String getNString(String parameterName) throws SQLException {
        return delegate().getNString(parameterName);
    }

    /**
     * @param parameterIndex
     * @param map
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getObject(int, java.util.Map)
     */
    public Object getObject(int parameterIndex, Map<String,Class<?>> map)
            throws SQLException {
        return delegate().getObject(parameterIndex, map);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getObject(int)
     */
    public Object getObject(int parameterIndex) throws SQLException {
        return delegate().getObject(parameterIndex);
    }

    /**
     * @param parameterName
     * @param map
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getObject(java.lang.String, java.util.Map)
     */
    public Object getObject(String parameterName, Map<String,Class<?>> map)
            throws SQLException {
        return delegate().getObject(parameterName, map);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getObject(java.lang.String)
     */
    public Object getObject(String parameterName) throws SQLException {
        return delegate().getObject(parameterName);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.PreparedStatement#getParameterMetaData()
     */
    public ParameterMetaData getParameterMetaData() throws SQLException {
        return delegate().getParameterMetaData();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getQueryTimeout()
     */
    public int getQueryTimeout() throws SQLException {
        return delegate().getQueryTimeout();
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getRef(int)
     */
    public Ref getRef(int parameterIndex) throws SQLException {
        return delegate().getRef(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getRef(java.lang.String)
     */
    public Ref getRef(String parameterName) throws SQLException {
        return delegate().getRef(parameterName);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getResultSet()
     */
    public ResultSet getResultSet() throws SQLException {
        return delegate().getResultSet();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getResultSetConcurrency()
     */
    public int getResultSetConcurrency() throws SQLException {
        return delegate().getResultSetConcurrency();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getResultSetHoldability()
     */
    public int getResultSetHoldability() throws SQLException {
        return delegate().getResultSetHoldability();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getResultSetType()
     */
    public int getResultSetType() throws SQLException {
        return delegate().getResultSetType();
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getRowId(int)
     */
    public RowId getRowId(int parameterIndex) throws SQLException {
        return delegate().getRowId(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getRowId(java.lang.String)
     */
    public RowId getRowId(String parameterName) throws SQLException {
        return delegate().getRowId(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getShort(int)
     */
    public short getShort(int parameterIndex) throws SQLException {
        return delegate().getShort(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getShort(java.lang.String)
     */
    public short getShort(String parameterName) throws SQLException {
        return delegate().getShort(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getSQLXML(int)
     */
    public SQLXML getSQLXML(int parameterIndex) throws SQLException {
        return delegate().getSQLXML(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getSQLXML(java.lang.String)
     */
    public SQLXML getSQLXML(String parameterName) throws SQLException {
        return delegate().getSQLXML(parameterName);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getString(int)
     */
    public String getString(int parameterIndex) throws SQLException {
        return delegate().getString(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getString(java.lang.String)
     */
    public String getString(String parameterName) throws SQLException {
        return delegate().getString(parameterName);
    }

    /**
     * @param parameterIndex
     * @param cal
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getTime(int, java.util.Calendar)
     */
    public Time getTime(int parameterIndex, Calendar cal) throws SQLException {
        return delegate().getTime(parameterIndex, cal);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getTime(int)
     */
    public Time getTime(int parameterIndex) throws SQLException {
        return delegate().getTime(parameterIndex);
    }

    /**
     * @param parameterName
     * @param cal
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getTime(java.lang.String, java.util.Calendar)
     */
    public Time getTime(String parameterName, Calendar cal) throws SQLException {
        return delegate().getTime(parameterName, cal);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getTime(java.lang.String)
     */
    public Time getTime(String parameterName) throws SQLException {
        return delegate().getTime(parameterName);
    }

    /**
     * @param parameterIndex
     * @param cal
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getTimestamp(int, java.util.Calendar)
     */
    public Timestamp getTimestamp(int parameterIndex, Calendar cal)
            throws SQLException {
        return delegate().getTimestamp(parameterIndex, cal);
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getTimestamp(int)
     */
    public Timestamp getTimestamp(int parameterIndex) throws SQLException {
        return delegate().getTimestamp(parameterIndex);
    }

    /**
     * @param parameterName
     * @param cal
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getTimestamp(java.lang.String, java.util.Calendar)
     */
    public Timestamp getTimestamp(String parameterName, Calendar cal)
            throws SQLException {
        return delegate().getTimestamp(parameterName, cal);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getTimestamp(java.lang.String)
     */
    public Timestamp getTimestamp(String parameterName) throws SQLException {
        return delegate().getTimestamp(parameterName);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getUpdateCount()
     */
    public int getUpdateCount() throws SQLException {
        return delegate().getUpdateCount();
    }

    /**
     * @param parameterIndex
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getURL(int)
     */
    public URL getURL(int parameterIndex) throws SQLException {
        return delegate().getURL(parameterIndex);
    }

    /**
     * @param parameterName
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#getURL(java.lang.String)
     */
    public URL getURL(String parameterName) throws SQLException {
        return delegate().getURL(parameterName);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#getWarnings()
     */
    public SQLWarning getWarnings() throws SQLException {
        return delegate().getWarnings();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#isClosed()
     */
    public boolean isClosed() throws SQLException {
        return delegate().isClosed();
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.Statement#isPoolable()
     */
    public boolean isPoolable() throws SQLException {
        return delegate().isPoolable();
    }

    /**
     * @param parameterIndex
     * @param sqlType
     * @param scale
     * @throws SQLException
     * @see java.sql.CallableStatement#registerOutParameter(int, int, int)
     */
    public void registerOutParameter(int parameterIndex, int sqlType, int scale)
            throws SQLException {
        delegate().registerOutParameter(parameterIndex, sqlType, scale);
    }

    /**
     * @param parameterIndex
     * @param sqlType
     * @param typeName
     * @throws SQLException
     * @see java.sql.CallableStatement#registerOutParameter(int, int, java.lang.String)
     */
    public void registerOutParameter(int parameterIndex,
                                     int sqlType,
                                     String typeName) throws SQLException {
        delegate().registerOutParameter(parameterIndex, sqlType, typeName);
    }

    /**
     * @param parameterIndex
     * @param sqlType
     * @throws SQLException
     * @see java.sql.CallableStatement#registerOutParameter(int, int)
     */
    public void registerOutParameter(int parameterIndex, int sqlType)
            throws SQLException {
        delegate().registerOutParameter(parameterIndex, sqlType);
    }

    /**
     * @param parameterName
     * @param sqlType
     * @param scale
     * @throws SQLException
     * @see java.sql.CallableStatement#registerOutParameter(java.lang.String, int, int)
     */
    public void registerOutParameter(String parameterName,
                                     int sqlType,
                                     int scale) throws SQLException {
        delegate().registerOutParameter(parameterName, sqlType, scale);
    }

    /**
     * @param parameterName
     * @param sqlType
     * @param typeName
     * @throws SQLException
     * @see java.sql.CallableStatement#registerOutParameter(java.lang.String, int, java.lang.String)
     */
    public void registerOutParameter(String parameterName,
                                     int sqlType,
                                     String typeName) throws SQLException {
        delegate().registerOutParameter(parameterName, sqlType, typeName);
    }

    /**
     * @param parameterName
     * @param sqlType
     * @throws SQLException
     * @see java.sql.CallableStatement#registerOutParameter(java.lang.String, int)
     */
    public void registerOutParameter(String parameterName, int sqlType)
            throws SQLException {
        delegate().registerOutParameter(parameterName, sqlType);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setArray(int, java.sql.Array)
     */
    public void setArray(int parameterIndex, Array x) throws SQLException {
        delegate().setArray(parameterIndex, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @param length
     * @throws SQLException
     * @see java.sql.PreparedStatement#setAsciiStream(int, java.io.InputStream, int)
     */
    public void setAsciiStream(int parameterIndex, InputStream x, int length)
            throws SQLException {
        delegate().setAsciiStream(parameterIndex, x, length);
    }

    /**
     * @param parameterIndex
     * @param x
     * @param length
     * @throws SQLException
     * @see java.sql.PreparedStatement#setAsciiStream(int, java.io.InputStream, long)
     */
    public void setAsciiStream(int parameterIndex, InputStream x, long length)
            throws SQLException {
        delegate().setAsciiStream(parameterIndex, x, length);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setAsciiStream(int, java.io.InputStream)
     */
    public void setAsciiStream(int parameterIndex, InputStream x)
            throws SQLException {
        delegate().setAsciiStream(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @param length
     * @throws SQLException
     * @see java.sql.CallableStatement#setAsciiStream(java.lang.String, java.io.InputStream, int)
     */
    public void setAsciiStream(String parameterName, InputStream x, int length)
            throws SQLException {
        delegate().setAsciiStream(parameterName, x, length);
    }

    /**
     * @param parameterName
     * @param x
     * @param length
     * @throws SQLException
     * @see java.sql.CallableStatement#setAsciiStream(java.lang.String, java.io.InputStream, long)
     */
    public void setAsciiStream(String parameterName, InputStream x, long length)
            throws SQLException {
        delegate().setAsciiStream(parameterName, x, length);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setAsciiStream(java.lang.String, java.io.InputStream)
     */
    public void setAsciiStream(String parameterName, InputStream x)
            throws SQLException {
        delegate().setAsciiStream(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setBigDecimal(int, java.math.BigDecimal)
     */
    public void setBigDecimal(int parameterIndex, BigDecimal x)
            throws SQLException {
        delegate().setBigDecimal(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setBigDecimal(java.lang.String, java.math.BigDecimal)
     */
    public void setBigDecimal(String parameterName, BigDecimal x)
            throws SQLException {
        delegate().setBigDecimal(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @param length
     * @throws SQLException
     * @see java.sql.PreparedStatement#setBinaryStream(int, java.io.InputStream, int)
     */
    public void setBinaryStream(int parameterIndex, InputStream x, int length)
            throws SQLException {
        delegate().setBinaryStream(parameterIndex, x, length);
    }

    /**
     * @param parameterIndex
     * @param x
     * @param length
     * @throws SQLException
     * @see java.sql.PreparedStatement#setBinaryStream(int, java.io.InputStream, long)
     */
    public void setBinaryStream(int parameterIndex, InputStream x, long length)
            throws SQLException {
        delegate().setBinaryStream(parameterIndex, x, length);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setBinaryStream(int, java.io.InputStream)
     */
    public void setBinaryStream(int parameterIndex, InputStream x)
            throws SQLException {
        delegate().setBinaryStream(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @param length
     * @throws SQLException
     * @see java.sql.CallableStatement#setBinaryStream(java.lang.String, java.io.InputStream, int)
     */
    public void setBinaryStream(String parameterName, InputStream x, int length)
            throws SQLException {
        delegate().setBinaryStream(parameterName, x, length);
    }

    /**
     * @param parameterName
     * @param x
     * @param length
     * @throws SQLException
     * @see java.sql.CallableStatement#setBinaryStream(java.lang.String, java.io.InputStream, long)
     */
    public void setBinaryStream(String parameterName, InputStream x, long length)
            throws SQLException {
        delegate().setBinaryStream(parameterName, x, length);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setBinaryStream(java.lang.String, java.io.InputStream)
     */
    public void setBinaryStream(String parameterName, InputStream x)
            throws SQLException {
        delegate().setBinaryStream(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setBlob(int, java.sql.Blob)
     */
    public void setBlob(int parameterIndex, Blob x) throws SQLException {
        delegate().setBlob(parameterIndex, x);
    }

    /**
     * @param parameterIndex
     * @param inputStream
     * @param length
     * @throws SQLException
     * @see java.sql.PreparedStatement#setBlob(int, java.io.InputStream, long)
     */
    public void setBlob(int parameterIndex, InputStream inputStream, long length)
            throws SQLException {
        delegate().setBlob(parameterIndex, inputStream, length);
    }

    /**
     * @param parameterIndex
     * @param inputStream
     * @throws SQLException
     * @see java.sql.PreparedStatement#setBlob(int, java.io.InputStream)
     */
    public void setBlob(int parameterIndex, InputStream inputStream)
            throws SQLException {
        delegate().setBlob(parameterIndex, inputStream);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setBlob(java.lang.String, java.sql.Blob)
     */
    public void setBlob(String parameterName, Blob x) throws SQLException {
        delegate().setBlob(parameterName, x);
    }

    /**
     * @param parameterName
     * @param inputStream
     * @param length
     * @throws SQLException
     * @see java.sql.CallableStatement#setBlob(java.lang.String, java.io.InputStream, long)
     */
    public void setBlob(String parameterName,
                        InputStream inputStream,
                        long length) throws SQLException {
        delegate().setBlob(parameterName, inputStream, length);
    }

    /**
     * @param parameterName
     * @param inputStream
     * @throws SQLException
     * @see java.sql.CallableStatement#setBlob(java.lang.String, java.io.InputStream)
     */
    public void setBlob(String parameterName, InputStream inputStream)
            throws SQLException {
        delegate().setBlob(parameterName, inputStream);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setBoolean(int, boolean)
     */
    public void setBoolean(int parameterIndex, boolean x) throws SQLException {
        delegate().setBoolean(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setBoolean(java.lang.String, boolean)
     */
    public void setBoolean(String parameterName, boolean x) throws SQLException {
        delegate().setBoolean(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setByte(int, byte)
     */
    public void setByte(int parameterIndex, byte x) throws SQLException {
        delegate().setByte(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setByte(java.lang.String, byte)
     */
    public void setByte(String parameterName, byte x) throws SQLException {
        delegate().setByte(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setBytes(int, byte[])
     */
    public void setBytes(int parameterIndex, byte[] x) throws SQLException {
        delegate().setBytes(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setBytes(java.lang.String, byte[])
     */
    public void setBytes(String parameterName, byte[] x) throws SQLException {
        delegate().setBytes(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param reader
     * @param length
     * @throws SQLException
     * @see java.sql.PreparedStatement#setCharacterStream(int, java.io.Reader, int)
     */
    public void setCharacterStream(int parameterIndex, Reader reader, int length)
            throws SQLException {
        delegate().setCharacterStream(parameterIndex, reader, length);
    }

    /**
     * @param parameterIndex
     * @param reader
     * @param length
     * @throws SQLException
     * @see java.sql.PreparedStatement#setCharacterStream(int, java.io.Reader, long)
     */
    public void setCharacterStream(int parameterIndex,
                                   Reader reader,
                                   long length) throws SQLException {
        delegate().setCharacterStream(parameterIndex, reader, length);
    }

    /**
     * @param parameterIndex
     * @param reader
     * @throws SQLException
     * @see java.sql.PreparedStatement#setCharacterStream(int, java.io.Reader)
     */
    public void setCharacterStream(int parameterIndex, Reader reader)
            throws SQLException {
        delegate().setCharacterStream(parameterIndex, reader);
    }

    /**
     * @param parameterName
     * @param reader
     * @param length
     * @throws SQLException
     * @see java.sql.CallableStatement#setCharacterStream(java.lang.String, java.io.Reader, int)
     */
    public void setCharacterStream(String parameterName,
                                   Reader reader,
                                   int length) throws SQLException {
        delegate().setCharacterStream(parameterName, reader, length);
    }

    /**
     * @param parameterName
     * @param reader
     * @param length
     * @throws SQLException
     * @see java.sql.CallableStatement#setCharacterStream(java.lang.String, java.io.Reader, long)
     */
    public void setCharacterStream(String parameterName,
                                   Reader reader,
                                   long length) throws SQLException {
        delegate().setCharacterStream(parameterName, reader, length);
    }

    /**
     * @param parameterName
     * @param reader
     * @throws SQLException
     * @see java.sql.CallableStatement#setCharacterStream(java.lang.String, java.io.Reader)
     */
    public void setCharacterStream(String parameterName, Reader reader)
            throws SQLException {
        delegate().setCharacterStream(parameterName, reader);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setClob(int, java.sql.Clob)
     */
    public void setClob(int parameterIndex, Clob x) throws SQLException {
        delegate().setClob(parameterIndex, x);
    }

    /**
     * @param parameterIndex
     * @param reader
     * @param length
     * @throws SQLException
     * @see java.sql.PreparedStatement#setClob(int, java.io.Reader, long)
     */
    public void setClob(int parameterIndex, Reader reader, long length)
            throws SQLException {
        delegate().setClob(parameterIndex, reader, length);
    }

    /**
     * @param parameterIndex
     * @param reader
     * @throws SQLException
     * @see java.sql.PreparedStatement#setClob(int, java.io.Reader)
     */
    public void setClob(int parameterIndex, Reader reader) throws SQLException {
        delegate().setClob(parameterIndex, reader);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setClob(java.lang.String, java.sql.Clob)
     */
    public void setClob(String parameterName, Clob x) throws SQLException {
        delegate().setClob(parameterName, x);
    }

    /**
     * @param parameterName
     * @param reader
     * @param length
     * @throws SQLException
     * @see java.sql.CallableStatement#setClob(java.lang.String, java.io.Reader, long)
     */
    public void setClob(String parameterName, Reader reader, long length)
            throws SQLException {
        delegate().setClob(parameterName, reader, length);
    }

    /**
     * @param parameterName
     * @param reader
     * @throws SQLException
     * @see java.sql.CallableStatement#setClob(java.lang.String, java.io.Reader)
     */
    public void setClob(String parameterName, Reader reader)
            throws SQLException {
        delegate().setClob(parameterName, reader);
    }

    /**
     * @param name
     * @throws SQLException
     * @see java.sql.Statement#setCursorName(java.lang.String)
     */
    public void setCursorName(String name) throws SQLException {
        delegate().setCursorName(name);
    }

    /**
     * @param parameterIndex
     * @param x
     * @param cal
     * @throws SQLException
     * @see java.sql.PreparedStatement#setDate(int, java.sql.Date, java.util.Calendar)
     */
    public void setDate(int parameterIndex, Date x, Calendar cal)
            throws SQLException {
        delegate().setDate(parameterIndex, x, cal);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setDate(int, java.sql.Date)
     */
    public void setDate(int parameterIndex, Date x) throws SQLException {
        delegate().setDate(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @param cal
     * @throws SQLException
     * @see java.sql.CallableStatement#setDate(java.lang.String, java.sql.Date, java.util.Calendar)
     */
    public void setDate(String parameterName, Date x, Calendar cal)
            throws SQLException {
        delegate().setDate(parameterName, x, cal);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setDate(java.lang.String, java.sql.Date)
     */
    public void setDate(String parameterName, Date x) throws SQLException {
        delegate().setDate(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setDouble(int, double)
     */
    public void setDouble(int parameterIndex, double x) throws SQLException {
        delegate().setDouble(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setDouble(java.lang.String, double)
     */
    public void setDouble(String parameterName, double x) throws SQLException {
        delegate().setDouble(parameterName, x);
    }

    /**
     * @param enable
     * @throws SQLException
     * @see java.sql.Statement#setEscapeProcessing(boolean)
     */
    public void setEscapeProcessing(boolean enable) throws SQLException {
        delegate().setEscapeProcessing(enable);
    }

    /**
     * @param direction
     * @throws SQLException
     * @see java.sql.Statement#setFetchDirection(int)
     */
    public void setFetchDirection(int direction) throws SQLException {
        delegate().setFetchDirection(direction);
    }

    /**
     * @param rows
     * @throws SQLException
     * @see java.sql.Statement#setFetchSize(int)
     */
    public void setFetchSize(int rows) throws SQLException {
        delegate().setFetchSize(rows);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setFloat(int, float)
     */
    public void setFloat(int parameterIndex, float x) throws SQLException {
        delegate().setFloat(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setFloat(java.lang.String, float)
     */
    public void setFloat(String parameterName, float x) throws SQLException {
        delegate().setFloat(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setInt(int, int)
     */
    public void setInt(int parameterIndex, int x) throws SQLException {
        delegate().setInt(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setInt(java.lang.String, int)
     */
    public void setInt(String parameterName, int x) throws SQLException {
        delegate().setInt(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setLong(int, long)
     */
    public void setLong(int parameterIndex, long x) throws SQLException {
        delegate().setLong(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setLong(java.lang.String, long)
     */
    public void setLong(String parameterName, long x) throws SQLException {
        delegate().setLong(parameterName, x);
    }

    /**
     * @param max
     * @throws SQLException
     * @see java.sql.Statement#setMaxFieldSize(int)
     */
    public void setMaxFieldSize(int max) throws SQLException {
        delegate().setMaxFieldSize(max);
    }

    /**
     * @param max
     * @throws SQLException
     * @see java.sql.Statement#setMaxRows(int)
     */
    public void setMaxRows(int max) throws SQLException {
        delegate().setMaxRows(max);
    }

    /**
     * @param parameterIndex
     * @param value
     * @param length
     * @throws SQLException
     * @see java.sql.PreparedStatement#setNCharacterStream(int, java.io.Reader, long)
     */
    public void setNCharacterStream(int parameterIndex,
                                    Reader value,
                                    long length) throws SQLException {
        delegate().setNCharacterStream(parameterIndex, value, length);
    }

    /**
     * @param parameterIndex
     * @param value
     * @throws SQLException
     * @see java.sql.PreparedStatement#setNCharacterStream(int, java.io.Reader)
     */
    public void setNCharacterStream(int parameterIndex, Reader value)
            throws SQLException {
        delegate().setNCharacterStream(parameterIndex, value);
    }

    /**
     * @param parameterName
     * @param value
     * @param length
     * @throws SQLException
     * @see java.sql.CallableStatement#setNCharacterStream(java.lang.String, java.io.Reader, long)
     */
    public void setNCharacterStream(String parameterName,
                                    Reader value,
                                    long length) throws SQLException {
        delegate().setNCharacterStream(parameterName, value, length);
    }

    /**
     * @param parameterName
     * @param value
     * @throws SQLException
     * @see java.sql.CallableStatement#setNCharacterStream(java.lang.String, java.io.Reader)
     */
    public void setNCharacterStream(String parameterName, Reader value)
            throws SQLException {
        delegate().setNCharacterStream(parameterName, value);
    }

    /**
     * @param parameterIndex
     * @param value
     * @throws SQLException
     * @see java.sql.PreparedStatement#setNClob(int, java.sql.NClob)
     */
    public void setNClob(int parameterIndex, NClob value) throws SQLException {
        delegate().setNClob(parameterIndex, value);
    }

    /**
     * @param parameterIndex
     * @param reader
     * @param length
     * @throws SQLException
     * @see java.sql.PreparedStatement#setNClob(int, java.io.Reader, long)
     */
    public void setNClob(int parameterIndex, Reader reader, long length)
            throws SQLException {
        delegate().setNClob(parameterIndex, reader, length);
    }

    /**
     * @param parameterIndex
     * @param reader
     * @throws SQLException
     * @see java.sql.PreparedStatement#setNClob(int, java.io.Reader)
     */
    public void setNClob(int parameterIndex, Reader reader) throws SQLException {
        delegate().setNClob(parameterIndex, reader);
    }

    /**
     * @param parameterName
     * @param value
     * @throws SQLException
     * @see java.sql.CallableStatement#setNClob(java.lang.String, java.sql.NClob)
     */
    public void setNClob(String parameterName, NClob value) throws SQLException {
        delegate().setNClob(parameterName, value);
    }

    /**
     * @param parameterName
     * @param reader
     * @param length
     * @throws SQLException
     * @see java.sql.CallableStatement#setNClob(java.lang.String, java.io.Reader, long)
     */
    public void setNClob(String parameterName, Reader reader, long length)
            throws SQLException {
        delegate().setNClob(parameterName, reader, length);
    }

    /**
     * @param parameterName
     * @param reader
     * @throws SQLException
     * @see java.sql.CallableStatement#setNClob(java.lang.String, java.io.Reader)
     */
    public void setNClob(String parameterName, Reader reader)
            throws SQLException {
        delegate().setNClob(parameterName, reader);
    }

    /**
     * @param parameterIndex
     * @param value
     * @throws SQLException
     * @see java.sql.PreparedStatement#setNString(int, java.lang.String)
     */
    public void setNString(int parameterIndex, String value)
            throws SQLException {
        delegate().setNString(parameterIndex, value);
    }

    /**
     * @param parameterName
     * @param value
     * @throws SQLException
     * @see java.sql.CallableStatement#setNString(java.lang.String, java.lang.String)
     */
    public void setNString(String parameterName, String value)
            throws SQLException {
        delegate().setNString(parameterName, value);
    }

    /**
     * @param parameterIndex
     * @param sqlType
     * @param typeName
     * @throws SQLException
     * @see java.sql.PreparedStatement#setNull(int, int, java.lang.String)
     */
    public void setNull(int parameterIndex, int sqlType, String typeName)
            throws SQLException {
        delegate().setNull(parameterIndex, sqlType, typeName);
    }

    /**
     * @param parameterIndex
     * @param sqlType
     * @throws SQLException
     * @see java.sql.PreparedStatement#setNull(int, int)
     */
    public void setNull(int parameterIndex, int sqlType) throws SQLException {
        delegate().setNull(parameterIndex, sqlType);
    }

    /**
     * @param parameterName
     * @param sqlType
     * @param typeName
     * @throws SQLException
     * @see java.sql.CallableStatement#setNull(java.lang.String, int, java.lang.String)
     */
    public void setNull(String parameterName, int sqlType, String typeName)
            throws SQLException {
        delegate().setNull(parameterName, sqlType, typeName);
    }

    /**
     * @param parameterName
     * @param sqlType
     * @throws SQLException
     * @see java.sql.CallableStatement#setNull(java.lang.String, int)
     */
    public void setNull(String parameterName, int sqlType) throws SQLException {
        delegate().setNull(parameterName, sqlType);
    }

    /**
     * @param parameterIndex
     * @param x
     * @param targetSqlType
     * @param scaleOrLength
     * @throws SQLException
     * @see java.sql.PreparedStatement#setObject(int, java.lang.Object, int, int)
     */
    public void setObject(int parameterIndex,
                          Object x,
                          int targetSqlType,
                          int scaleOrLength) throws SQLException {
        delegate().setObject(parameterIndex, x, targetSqlType, scaleOrLength);
    }

    /**
     * @param parameterIndex
     * @param x
     * @param targetSqlType
     * @throws SQLException
     * @see java.sql.PreparedStatement#setObject(int, java.lang.Object, int)
     */
    public void setObject(int parameterIndex, Object x, int targetSqlType)
            throws SQLException {
        delegate().setObject(parameterIndex, x, targetSqlType);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setObject(int, java.lang.Object)
     */
    public void setObject(int parameterIndex, Object x) throws SQLException {
        delegate().setObject(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @param targetSqlType
     * @param scale
     * @throws SQLException
     * @see java.sql.CallableStatement#setObject(java.lang.String, java.lang.Object, int, int)
     */
    public void setObject(String parameterName,
                          Object x,
                          int targetSqlType,
                          int scale) throws SQLException {
        delegate().setObject(parameterName, x, targetSqlType, scale);
    }

    /**
     * @param parameterName
     * @param x
     * @param targetSqlType
     * @throws SQLException
     * @see java.sql.CallableStatement#setObject(java.lang.String, java.lang.Object, int)
     */
    public void setObject(String parameterName, Object x, int targetSqlType)
            throws SQLException {
        delegate().setObject(parameterName, x, targetSqlType);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setObject(java.lang.String, java.lang.Object)
     */
    public void setObject(String parameterName, Object x) throws SQLException {
        delegate().setObject(parameterName, x);
    }

    /**
     * @param poolable
     * @throws SQLException
     * @see java.sql.Statement#setPoolable(boolean)
     */
    public void setPoolable(boolean poolable) throws SQLException {
        delegate().setPoolable(poolable);
    }

    /**
     * @param seconds
     * @throws SQLException
     * @see java.sql.Statement#setQueryTimeout(int)
     */
    public void setQueryTimeout(int seconds) throws SQLException {
        delegate().setQueryTimeout(seconds);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setRef(int, java.sql.Ref)
     */
    public void setRef(int parameterIndex, Ref x) throws SQLException {
        delegate().setRef(parameterIndex, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setRowId(int, java.sql.RowId)
     */
    public void setRowId(int parameterIndex, RowId x) throws SQLException {
        delegate().setRowId(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setRowId(java.lang.String, java.sql.RowId)
     */
    public void setRowId(String parameterName, RowId x) throws SQLException {
        delegate().setRowId(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setShort(int, short)
     */
    public void setShort(int parameterIndex, short x) throws SQLException {
        delegate().setShort(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setShort(java.lang.String, short)
     */
    public void setShort(String parameterName, short x) throws SQLException {
        delegate().setShort(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param xmlObject
     * @throws SQLException
     * @see java.sql.PreparedStatement#setSQLXML(int, java.sql.SQLXML)
     */
    public void setSQLXML(int parameterIndex, SQLXML xmlObject)
            throws SQLException {
        delegate().setSQLXML(parameterIndex, xmlObject);
    }

    /**
     * @param parameterName
     * @param xmlObject
     * @throws SQLException
     * @see java.sql.CallableStatement#setSQLXML(java.lang.String, java.sql.SQLXML)
     */
    public void setSQLXML(String parameterName, SQLXML xmlObject)
            throws SQLException {
        delegate().setSQLXML(parameterName, xmlObject);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setString(int, java.lang.String)
     */
    public void setString(int parameterIndex, String x) throws SQLException {
        delegate().setString(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setString(java.lang.String, java.lang.String)
     */
    public void setString(String parameterName, String x) throws SQLException {
        delegate().setString(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @param cal
     * @throws SQLException
     * @see java.sql.PreparedStatement#setTime(int, java.sql.Time, java.util.Calendar)
     */
    public void setTime(int parameterIndex, Time x, Calendar cal)
            throws SQLException {
        delegate().setTime(parameterIndex, x, cal);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setTime(int, java.sql.Time)
     */
    public void setTime(int parameterIndex, Time x) throws SQLException {
        delegate().setTime(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @param cal
     * @throws SQLException
     * @see java.sql.CallableStatement#setTime(java.lang.String, java.sql.Time, java.util.Calendar)
     */
    public void setTime(String parameterName, Time x, Calendar cal)
            throws SQLException {
        delegate().setTime(parameterName, x, cal);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setTime(java.lang.String, java.sql.Time)
     */
    public void setTime(String parameterName, Time x) throws SQLException {
        delegate().setTime(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @param cal
     * @throws SQLException
     * @see java.sql.PreparedStatement#setTimestamp(int, java.sql.Timestamp, java.util.Calendar)
     */
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal)
            throws SQLException {
        delegate().setTimestamp(parameterIndex, x, cal);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setTimestamp(int, java.sql.Timestamp)
     */
    public void setTimestamp(int parameterIndex, Timestamp x)
            throws SQLException {
        delegate().setTimestamp(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param x
     * @param cal
     * @throws SQLException
     * @see java.sql.CallableStatement#setTimestamp(java.lang.String, java.sql.Timestamp, java.util.Calendar)
     */
    public void setTimestamp(String parameterName, Timestamp x, Calendar cal)
            throws SQLException {
        delegate().setTimestamp(parameterName, x, cal);
    }

    /**
     * @param parameterName
     * @param x
     * @throws SQLException
     * @see java.sql.CallableStatement#setTimestamp(java.lang.String, java.sql.Timestamp)
     */
    public void setTimestamp(String parameterName, Timestamp x)
            throws SQLException {
        delegate().setTimestamp(parameterName, x);
    }

    /**
     * @param parameterIndex
     * @param x
     * @param length
     * @throws SQLException
     * @deprecated
     * @see java.sql.PreparedStatement#setUnicodeStream(int, java.io.InputStream, int)
     */
    public void setUnicodeStream(int parameterIndex, InputStream x, int length)
            throws SQLException {
        delegate().setUnicodeStream(parameterIndex, x, length);
    }

    /**
     * @param parameterIndex
     * @param x
     * @throws SQLException
     * @see java.sql.PreparedStatement#setURL(int, java.net.URL)
     */
    public void setURL(int parameterIndex, URL x) throws SQLException {
        delegate().setURL(parameterIndex, x);
    }

    /**
     * @param parameterName
     * @param val
     * @throws SQLException
     * @see java.sql.CallableStatement#setURL(java.lang.String, java.net.URL)
     */
    public void setURL(String parameterName, URL val) throws SQLException {
        delegate().setURL(parameterName, val);
    }

    /**
     * @return
     * @throws SQLException
     * @see java.sql.CallableStatement#wasNull()
     */
    public boolean wasNull() throws SQLException {
        return delegate().wasNull();
    }

    
}
